python generate_data.py \
--filesize=4 \
--num_tfrecords=2 \
--threads=2 \
--outpath=records \
--max_vertices=300 \
--imagespath="." \
--ocrpath="." \
--tablepath="." \
--visualizeimgs=1 \
--visualizebboxes=1