python generate_data.py \
--filesize=4 \
--num_tfrecords=2 \
--threads=2 \
--outpath=results \
--max_vertices=600 \
--imagespath="." \
--ocrpath="." \
--tablepath="." \
--visualizeimgs=1 \
--visualizebboxes=1